# Файл docker-compose должен начинаться с тега версии.
# Мы используем "3" так как это - самая свежая версия на момент написания этого кода.

version: "3"

# Следует учитывать, что docker-composes работает с сервисами.
# 1 сервис = 1 контейнер.
# Сервисом может быть клиент, сервер, сервер баз данных...
# Раздел, в котором будут описаны сервисы, начинается с 'services'.

services:
  # Имя сервера
  docker_part5:

    # Ключевое слово "build" позволяет задать
    # путь к файлу Dockerfile, который нужно использовать для создания образа,
    # который позволит запустить сервис.
    # Здесь 'server/' соответствует пути к папке сервера,
    # которая содержит соответствующий Dockerfile.
    build: docker_part5/

    # Имя контейнера
    container_name: part5

  nginx:
    image: nginx
    container_name: nginx

    # Проброс портов с локалки на докер
    ports:
      - "80:8080"

    # Монтирование файла nginx.conf внутрь докера
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
